//
//  DeveloperPreview.swift
//  AirbnbClone
//
//  Created by Esse Jacques  on 30/05/2024.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview();
    
    var mockListings: [Listing] = [
        Listing(id: UUID().uuidString,
                ownerUid: "owner1",
                ownerName: "John Doe",
                ownerImageUrl: "john_doe_profile_image",
                numberOfBedrooms: 3,
                numberOfBathrooms: 2,
                numberOfGuests: 6,
                numberOfBeds: 4,
                pricePerNigth: 150,
                latitude: 37.7749,
                longgitude: -122.4194,
                address: "123 Main St",
                city: "San Francisco",
                state: "CA",
                title: "Modern Apartment with Stunning Views",
                rating: 4.8,
                features: [.superHost, .selfChekin],
                amentities: [.wifi, .tv, .balcony],
                type: .apartment),
        Listing(id:  UUID().uuidString,
                ownerUid: "owner2",
                ownerName: "Jane Smith",
                ownerImageUrl: "jane_smith_profile_image",
                numberOfBedrooms: 2,
                numberOfBathrooms: 1,
                numberOfGuests: 4,
                numberOfBeds: 2,
                pricePerNigth: 120,
                latitude: 34.0522,
                longgitude: -118.2437,
                address: "456 Oak St",
                city: "Los Angeles",
                state: "CA",
                title: "Cozy House near Hollywood",
                rating: 4.5,
                features: [.selfChekin],
                amentities: [.wifi, .tv],
                type: .house),
        Listing(id:  UUID().uuidString,
                ownerUid: "owner3",
                ownerName: "Alice Johnson",
                ownerImageUrl: "alice_johnson_profile_image",
                numberOfBedrooms: 1,
                numberOfBathrooms: 1,
                numberOfGuests: 2,
                numberOfBeds: 1,
                pricePerNigth: 80,
                latitude: 40.7128,
                longgitude: -74.0060,
                address: "789 Maple Ave",
                city: "New York",
                state: "NY",
                title: "Charming Studio in Manhattan",
                rating: 4.7,
                features: [.selfChekin],
                amentities: [.wifi],
                type: .apartment),
        Listing(id: UUID().uuidString,
                    ownerUid: "owner4",
                    ownerName: "Michael Johnson",
                    ownerImageUrl: "michael_johnson_profile_image",
                    numberOfBedrooms: 2,
                    numberOfBathrooms: 1,
                    numberOfGuests: 4,
                    numberOfBeds: 2,
                    pricePerNigth: 100,
                    latitude: 41.8781,
                    longgitude: -87.6298,
                    address: "1010 Pine St",
                    city: "Chicago",
                    state: "IL",
                    title: "Spacious Loft in Downtown Chicago",
                    rating: 4.6,
                    features: [.selfChekin],
                    amentities: [.wifi, .tv],
                    type: .apartment),
            // Listing 5
            Listing(id: UUID().uuidString,
                    ownerUid: "owner5",
                    ownerName: "Emily Brown",
                    ownerImageUrl: "emily_brown_profile_image",
                    numberOfBedrooms: 3,
                    numberOfBathrooms: 2,
                    numberOfGuests: 6,
                    numberOfBeds: 4,
                    pricePerNigth: 180,
                    latitude: 45.5051,
                    longgitude: -122.6750,
                    address: "123 Oak St",
                    city: "Portland",
                    state: "OR",
                    title: "Luxury Condo with River View",
                    rating: 4.9,
                    features: [.superHost],
                    amentities: [.pool, .wifi, .tv, .balcony],
                    type: .apartment),
            // Listing 6
            Listing(id: UUID().uuidString,
                    ownerUid: "owner6",
                    ownerName: "Chris Wilson",
                    ownerImageUrl: "chris_wilson_profile_image",
                    numberOfBedrooms: 4,
                    numberOfBathrooms: 3,
                    numberOfGuests: 8,
                    numberOfBeds: 5,
                    pricePerNigth: 250,
                    latitude: 33.7490,
                    longgitude: -84.3880,
                    address: "456 Pine St",
                    city: "Atlanta",
                    state: "GA",
                    title: "Elegant Mansion in Buckhead",
                    rating: 5.0,
                    features: [.superHost],
                    amentities: [.pool, .wifi, .tv, .alarmSystem, .office, .balcony],
                    type: .villa),
            // Listing 7
            Listing(id:  UUID().uuidString,
                    ownerUid: "owner7",
                    ownerName: "Jessica Martinez",
                    ownerImageUrl: "jessica_martinez_profile_image",
                    numberOfBedrooms: 2,
                    numberOfBathrooms: 1,
                    numberOfGuests: 4,
                    numberOfBeds: 2,
                    pricePerNigth: 110,
                    latitude: 37.3382,
                    longgitude: -121.8863,
                    address: "789 Elm St",
                    city: "San Jose",
                    state: "CA",
                    title: "Quaint Cottage near Downtown",
                    rating: 4.3,
                    features: [.selfChekin],
                    amentities: [.wifi, .tv],
                    type: .house),
            // Listing 8
            Listing(id:  UUID().uuidString,
                    ownerUid: "owner8",
                    ownerName: "Matthew Davis",
                    ownerImageUrl: "matthew_davis_profile_image",
                    numberOfBedrooms: 3,
                    numberOfBathrooms: 2,
                    numberOfGuests: 6,
                    numberOfBeds: 3,
                    pricePerNigth: 140,
                    latitude: 32.7767,
                    longgitude: -96.7970,
                    address: "1010 Maple St",
                    city: "Dallas",
                    state: "TX",
                    title: "Downtown Penthouse with Skyline View",
                    rating: 4.7,
                    features: [.superHost, .selfChekin],
                    amentities: [.wifi, .tv, .balcony],
                    type: .apartment),
            // Listing 9
            Listing(id:  UUID().uuidString,
                    ownerUid: "owner9",
                    ownerName: "Sarah Thompson",
                    ownerImageUrl: "sarah_thompson_profile_image",
                    numberOfBedrooms: 4,
                    numberOfBathrooms: 3,
                    numberOfGuests: 8,
                    numberOfBeds: 5,
                    pricePerNigth: 220,
                    latitude: 39.9526,
                    longgitude: -75.1652,
                    address: "456 Pine St",
                    city: "Philadelphia",
                    state: "PA",
                    title: "Historic Townhouse in Center City",
                    rating: 4.9,
                    features: [.superHost],
                    amentities: [.wifi, .tv],
                    type: .townHouse),
            // Listing 10
            Listing(id:  UUID().uuidString,
                    ownerUid: "owner10",
                    ownerName: "David Lee",
                    ownerImageUrl: "david_lee_profile_image",
                    numberOfBedrooms: 3,
                    numberOfBathrooms: 2,
                    numberOfGuests: 6,
                    numberOfBeds: 4,
                    pricePerNigth: 160,
                    latitude: 42.3601,
                    longgitude: -71.0589,
                    address: "123 Pine St",
                    city: "Boston",
                    state: "MA",
                    title: "Cozy Loft in Beacon Hill",
                    rating: 4.5,
                    features: [.selfChekin],
                    amentities: [.wifi, .tv],
                    type: .apartment),
            // 11
        Listing(id: UUID().uuidString,
                 ownerUid: "owner3",
                 ownerName: "Alice Johnson",
                 ownerImageUrl: "alice_johnson_profile_image",
                 numberOfBedrooms: 4,
                 numberOfBathrooms: 3,
                 numberOfGuests: 8,
                 numberOfBeds: 5,
                 pricePerNigth: 200,
                 latitude: 51.5074,
                 longgitude: -0.1278,
                 address: "789 Oxford St",
                 city: "London",
                 state: "UK",
                 title: "Luxurious Villa in London",
                 rating: 4.9,
                 features: [.superHost],
                 amentities: [.pool,.wifi,.office],
                 type:.villa),
        // 12
        Listing(id: UUID().uuidString,
                ownerUid: "owner4",
                ownerName: "Bob Brown",
                ownerImageUrl: "bob_brown_profile_image",
                numberOfBedrooms: 1,
                numberOfBathrooms: 1,
                numberOfGuests: 2,
                numberOfBeds: 2,
                pricePerNigth: 80,
                latitude: 48.8566,
                longgitude: 2.3522,
                address: "101 Rue de Rivoli",
                city: "Paris",
                state: "FR",
                title: "Cozy Studio in Paris",
                rating: 4.3,
                features: [.selfChekin],
                amentities: [.wifi, .office],
                type:.villa),
        // Exemple 13
        Listing(id: UUID().uuidString,
                ownerUid: "owner5",
                ownerName: "Charlie White",
                ownerImageUrl: "charlie_white_profile_image",
                numberOfBedrooms: 5,
                numberOfBathrooms: 4,
                numberOfGuests: 10,
                numberOfBeds: 6,
                pricePerNigth: 300,
                latitude: 35.6895,
                longgitude: 139.6917,
                address: "Tokyo Tower",
                city: "Tokyo",
                state: "JP",
                title: "Spectacular Penthouse in Tokyo",
                rating: 4.7,
                features: [.superHost],
                amentities: [.pool,.balcony,.office],
                type:.apartment),
        // Exemple 14
        Listing(id: UUID().uuidString,
                ownerUid: "owner6",
                ownerName: "Diana Green",
                ownerImageUrl: "diana_green_profile_image",
                numberOfBedrooms: 2,
                numberOfBathrooms: 2,
                numberOfGuests: 4,
                numberOfBeds: 3,
                pricePerNigth: 130,
                latitude: 41.8781,
                longgitude: -87.6298,
                address: "1600 Pennsylvania Ave NW",
                city: "Washington D.C.",
                state: "DC",
                title: "Historic Mansion near White House",
                rating: 4.6,
                features: [.selfChekin],
                amentities: [.wifi,.office,.landry, .pool],
                type:.townHouse),
        
        Listing(id: UUID().uuidString,
                    ownerUid: "owner7",
                    ownerName: "Eva Black",
                    ownerImageUrl: "eva_black_profile_image",
                    numberOfBedrooms: 4,
                    numberOfBathrooms: 3,
                    numberOfGuests: 8,
                    numberOfBeds: 5,
                    pricePerNigth: 250,
                    latitude: 55.7558,
                    longgitude: 37.6173,
                    address: "Kremlin Place",
                    city: "Moscow",
                    state: "RU",
                    title: "Imperial Estate near Kremlin",
                    rating: 4.4,
                    features: [.selfChekin],
                amentities: [.wifi,.pool,.tv],
                type:.house),
            // Exemple 8
            Listing(id: UUID().uuidString,
                    ownerUid: "owner8",
                    ownerName: "Frank Red",
                    ownerImageUrl: "frank_red_profile_image",
                    numberOfBedrooms: 3,
                    numberOfBathrooms: 2,
                    numberOfGuests: 6,
                    numberOfBeds: 4,
                    pricePerNigth: 180,
                    latitude: 52.5200,
                    longgitude: 13.4050,
                    address: "Brandenburg Gate",
                    city: "Berlin",
                    state: "DE",
                    title: "Chic Loft in Berlin Center",
                    rating: 4.2,
                    features: [.superHost],
                    amentities: [.wifi,.landry,.office],
                    type:.villa),
            // Exemple 9
            Listing(id: UUID().uuidString,
                    ownerUid: "owner9",
                    ownerName: "Grace Blue",
                    ownerImageUrl: "grace_blue_profile_image",
                    numberOfBedrooms: 2,
                    numberOfBathrooms: 2,
                    numberOfGuests: 4,
                    numberOfBeds: 3,
                    pricePerNigth: 110,
                    latitude: 43.6532,
                    longgitude: -79.3832,
                    address: "CN Tower",
                    city: "Toronto",
                    state: "ON",
                    title: "Sky-High Suite with CN Tower View",
                    rating: 4.5,
                    features: [.selfChekin],
                    amentities: [.wifi,.balcony, .tv],
                    type:.villa),
    ]

}
